- custom_components/solaredge_modbus/__init__.py
- custom_components/solaredge_modbus/manifest.json
* Bump pymodbus to 2.5.3
* Make a new TCP connection to the inverter every polling cycle.
* Tested with 15 second polling interval.
> Bump pymodbus to 2.5.3

- custom_components/solaredge_modbus/__init__.py
Missed changing one unit id to a variable in meter read section
> Missed a unit id assignment

- custom_components/solaredge_modbus/__init__.py
- custom_components/solaredge_modbus/const.py
- custom_components/solaredge_modbus/sensor.py
* Add "option" sensor to inverter section
* Add status codes for Fronius
* Temperature not supported on Fronius
> Add support for Fronius inverters

- custom_components/solaredge_modbus_multi/hub.py
> Check for duplicate meter serial numbers

- custom_components/solaredge_modbus_multi/translations/pl.json
Polish translation from @bdkacz
> Add Polish language translation

- custom_components/solaredge_modbus_multi/__init__.py
- custom_components/solaredge_modbus_multi/hub.py
Observed connection being held open across reconfigure.
> Refactor shutdown function

- custom_components/solaredge_modbus_multi/hub.py
Revert unnecessary changes (did not help with issue #80) to modbus client object.
> Modbus Client Object

- custom_components/solaredge_modbus_multi/__init__.py
- custom_components/solaredge_modbus_multi/hub.py
Add support for removing devices that are no longer valid or installed from the UI.
> Support removing devices from UI

- custom_components/solaredge_modbus_multi/hub.py
Add logging in debug so we don't have to ask people what their config is.
> Add integration config debug logging

- custom_components/solaredge_modbus_multi/hub.py
This should have been part of PR #81 but was overlooked.
> Qualify read exceptions during setup

- custom_components/solaredge_modbus_multi/hub.py
- custom_components/solaredge_modbus_multi/sensor.py
Log floats as hex because the float value is unhelpful in debugging
> Battery log float as hex

- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/manifest.json
- custom_components/solaredge_modbus_multi/sensor.py
Add BatteryLimit class for min and max voltage range, min and max current range.
Remove equality checks involving floats since it's not reliable.
Validate max and available energy against the rated (nameplate) capacity. Neither should ever be higher than nameplate capacity.
Validate temperature against a reasonable range of min/max values.
> Update battery data validations

- custom_components/solaredge_modbus_multi/sensor.py
Support new entity naming practices in Home Assistant.
* https://developers.home-assistant.io/blog/2022/07/10/entity_naming
* https://developers.home-assistant.io/docs/core/entity#entity-naming
> Support new entity naming practices

- custom_components/solaredge_modbus_multi/hub.py
This PR provides better error messages during initialization or after adding to HA.
> Differentiate no response vs. not sunspec modbus

- .github/workflows/python-quality.yaml
- custom_components/solaredge_modbus_multi/helpers.py
Use my own action for isort, black, and flak8 because the previous one was too out of date.
> Change python code quality action

- custom_components/solaredge_modbus_multi/__init__.py
- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/hub.py
- custom_components/solaredge_modbus_multi/number.py
- custom_components/solaredge_modbus_multi/select.py
Reverts WillCodeForCats/solaredge-modbus-multi#153
> Revert "Revert "Add support for storedge control""

- custom_components/solaredge_modbus_multi/hub.py
- custom_components/solaredge_modbus_multi/sensor.py
Add MMPPT Events sensor for SolarEdge Synergy inverters
> Add Synergy MMPPT Events sensor

- custom_components/solaredge_modbus_multi/manifest.json
- requirements.txt
> Bump pymodbus to 3.0.1

- custom_components/solaredge_modbus_multi/sensor.py
Pad mmppt events bit display attribute
> Pad mmppt events bit display attribute

- custom_components/solaredge_modbus_multi/hub.py
> Clean up debug logging

- custom_components/solaredge_modbus_multi/hub.py
Fix for inverters without limit control
> Fix for inverters without limit control

- custom_components/solaredge_modbus_multi/sensor.py
Allow display of zero if option to allow reset to zero is enabled. Followup for PR #195
> Add batt energy reset option to validation logic

- custom_components/solaredge_modbus_multi/manifest.json
Add integration_type to manifest.
> Add integration_type to manifest

- custom_components/solaredge_modbus_multi/const.py
Python 3.11 StrEnum with backwards compatibility.
> Python 3.11 StrEnum

- custom_components/solaredge_modbus_multi/__init__.py
- custom_components/solaredge_modbus_multi/config_flow.py
- custom_components/solaredge_modbus_multi/const.py
I wasn't using the Flag enum type properly, change to IntEnum and use bool() instead.
> ChangeConfDefaultFlag enum type

- custom_components/solaredge_modbus_multi/manifest.json
- custom_components/solaredge_modbus_multi/number.py
- custom_components/solaredge_modbus_multi/sensor.py
- hacs.json
> Home assistant core 2022.11

- custom_components/solaredge_modbus_multi/__init__.py
- custom_components/solaredge_modbus_multi/config_flow.py
- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/hub.py
- custom_components/solaredge_modbus_multi/sensor.py
- custom_components/solaredge_modbus_multi/strings.json
- custom_components/solaredge_modbus_multi/translations/de.json
- custom_components/solaredge_modbus_multi/translations/en.json
- custom_components/solaredge_modbus_multi/translations/fr.json
- custom_components/solaredge_modbus_multi/translations/nb.json
- custom_components/solaredge_modbus_multi/translations/nl.json
- custom_components/solaredge_modbus_multi/translations/pl.json
New config flow for battery options.
Add battery rating adjustment option to config flow.
> Battery rating adjustment config option

- README.md
- custom_components/solaredge_modbus_multi/sensor.py
- hacs.json
- info.md
> Home Assistant Core 2023.1

- custom_components/solaredge_modbus_multi/helpers.py
- custom_components/solaredge_modbus_multi/sensor.py
Add support for sensor entity native rounding new in HA 2023.2
> Sensor entity native rounding for HA 2023.2

- custom_components/solaredge_modbus_multi/sensor.py
HA core removed native_precision introduced in 2023.2
This is currently in HA dev branch and will probably be released in HA 2023.3 unless they change it again.
> HA core change for rounding

- custom_components/solaredge_modbus_multi/__init__.py
> Add type hints to coordinator

- custom_components/solaredge_modbus_multi/diagnostics.py
Add devices to diagnostic output
> Add devices to diagnostic output

- custom_components/solaredge_modbus_multi/sensor.py
Always show mmppt event attributes, even if the event is not defined.
> Always show mmppt event attributes

- custom_components/solaredge_modbus_multi/__init__.py
- custom_components/solaredge_modbus_multi/manifest.json
Increase starting wait to 800 ms
> Increase starting wait to 800 ms

- custom_components/solaredge_modbus_multi/__init__.py
- custom_components/solaredge_modbus_multi/const.py
Add retry settings const so that it's easier for people who want to modify these settings to do so without having to look at code.
> Add retry settings const

- custom_components/solaredge_modbus_multi/const.py
> Add observed error codes

- custom_components/solaredge_modbus_multi/hub.py
Set mmppt dict to none if units are invalid
> Set mmppt dict to none if units are invalid

- custom_components/solaredge_modbus_multi/hub.py
Use the DeviceInfo helper instead of a dict. Basically the same thing but this is using an HA provided class and type.
> Use the DeviceInfo helper

- custom_components/solaredge_modbus_multi/config_flow.py
- custom_components/solaredge_modbus_multi/repairs.py
* Remove unnecessary function _host_in_configuration_exists
* Always lowercase host name string
* Remove legacy connection class definition not used since 2021.6.0
* Update docstrings
* Add typing for async_step_user
> Code quality improvements for config flow

- custom_components/solaredge_modbus_multi/hub.py
* Update the inverter command write function based on simulated conditions.
* Add debug logging to writes
* Raise better error messages to Home Assistant
> Update inverter command function

- README.md
- custom_components/solaredge_modbus_multi/__init__.py
- custom_components/solaredge_modbus_multi/config_flow.py
- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/hub.py
- custom_components/solaredge_modbus_multi/manifest.json
- hacs.json
- info.md
- requirements.txt
While working on function checking the new grid switch added in PR #352 and #359, this ended up going down a rabbit hole of mostly unplanned changes that resulted in this branch.
This is a major internal architectural change for a v2.4.0 release instead of something on the v2.3.x releases.
> Improved async

- custom_components/solaredge_modbus_multi/hub.py
Reverts WillCodeForCats/solaredge-modbus-multi#381
> Revert "Change battery device check"

- custom_components/solaredge_modbus_multi/__init__.py
- custom_components/solaredge_modbus_multi/button.py
- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/hub.py
Reverts WillCodeForCats/solaredge-modbus-multi#378
May not be compatible with inverters that go unresponsive after commands.
> Revert "Skip offline inverters when updating"

- custom_components/solaredge_modbus_multi/hub.py
Make inverter command delay locking so that HA waits when sending multiple commands.
> Make inverter command delay locking

- custom_components/solaredge_modbus_multi/__init__.py
- custom_components/solaredge_modbus_multi/config_flow.py
- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/hub.py
- custom_components/solaredge_modbus_multi/strings.json
- custom_components/solaredge_modbus_multi/translations/de.json
- custom_components/solaredge_modbus_multi/translations/en.json
- custom_components/solaredge_modbus_multi/translations/fr.json
- custom_components/solaredge_modbus_multi/translations/nb.json
- custom_components/solaredge_modbus_multi/translations/nl.json
- custom_components/solaredge_modbus_multi/translations/pl.json
Add modbus client timeout option (default 3 seconds)
> Add modbus client timeout option

- custom_components/solaredge_modbus_multi/hub.py
- custom_components/solaredge_modbus_multi/sensor.py
CosPhi, Active Power Limit, RRCR Status
> Some sensors weren't using platform uid base

- custom_components/solaredge_modbus_multi/__init__.py
- custom_components/solaredge_modbus_multi/binary_sensor.py
- custom_components/solaredge_modbus_multi/hub.py
- custom_components/solaredge_modbus_multi/sensor.py
- custom_components/solaredge_modbus_multi/switch.py
Also revert all the additional debug logging
> Add power control options option property

- README.md
- custom_components/solaredge_modbus_multi/manifest.json
- hacs.json
- info.md
- requirements.txt
Pin requirement for pymodbus to 3.4.1 to match expected release in Home Assistant 2023.9
> Pymodbus 3.4.1

- custom_components/solaredge_modbus_multi/hub.py
Compare number of requested registers to length of received registers.
> Compare requested to received

- README.md
- custom_components/solaredge_modbus_multi/manifest.json
- info.md
- requirements.txt
Pymodbus 3.5.2 doesn't have any changes that affect this integration
> Set min pymodbus to 3.5.1

- custom_components/solaredge_modbus_multi/const.py
> Set charge/discharge limit constants to 1MW

- custom_components/solaredge_modbus_multi/const.py
Moving this class to the top so it's easy to find if someone wants to try different retry values.
> Move RetrySettings class to top

- custom_components/solaredge_modbus_multi/helpers.py
Raise TypeError from struct.error in helper
> Raise TypeError from struct.error in helper

- custom_components/solaredge_modbus_multi/const.py
> Increase retry limit by 1

- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/hub.py
Messages are not clear what they mean. I knew what it meant but this is clearer.
> Update received requested logging

- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/hub.py
Add ReconnectDelayMax to const.py
> Add ReconnectDelayMax to const.py

- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/hub.py
This reverts commit 445fe32000b6f5f3c205ce6b4adf96d2acfd227b.
> Revert "Revert "Add ReconnectDelayMax to const.py""

- README.md
- hacs.json
- info.md
Update minimum version of Home Assistant to 2023.11.0
> Min version HA 2023.12.0

- README.md
- custom_components/solaredge_modbus_multi/hub.py
- info.md
Add support for third battery reported at offset 0x200 from battery 2 in discussion #233.
> Add support for third battery

- custom_components/solaredge_modbus_multi/strings.json
- custom_components/solaredge_modbus_multi/translations/en.json
- custom_components/solaredge_modbus_multi/translations/it.json
Fix spelling in English translation
> Fix spelling in English translation

- custom_components/solaredge_modbus_multi/translations/it.json
> Add Italian translation

- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/hub.py
Update to make adding any future additional battery addresses as simple as updating BATTERY_REG_BASE without any code changes.
> Refactor battery detection

- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/hub.py
Refactor meter detection using the same method as Refactor battery detection PR #509
> Refactor meter detection

- custom_components/solaredge_modbus_multi/hub.py
Catch ModbusIOException from setup as seen from logs in issue #514.
> Catch ModbusIOException from setup

- custom_components/solaredge_modbus_multi/binary_sensor.py
- custom_components/solaredge_modbus_multi/button.py
Remove redundant init definitions.
> Cleanup for button and binary sensor entities

- custom_components/solaredge_modbus_multi/button.py
> Add refresh icon

- custom_components/solaredge_modbus_multi/button.py
- custom_components/solaredge_modbus_multi/sensor.py
Add power commit and restore buttons with sensors
> Add power commit and restore buttons with sensors

- custom_components/solaredge_modbus_multi/hub.py
Clear repair issue if raised during setup. Previous repairs were only cleared when raised during regular polling cycles.
> Clear repair issue if raised during setup

- custom_components/solaredge_modbus_multi/number.py
- custom_components/solaredge_modbus_multi/sensor.py
Match typing and casting in number platform
> Match typing and casting in number platform

- custom_components/solaredge_modbus_multi/sensor.py
Round CosPhi to 1 place and type as float to match number entity.
> Round CosPhi to 1 place and type as float

- custom_components/solaredge_modbus_multi/sensor.py
Remove unnecessary init defs from sensor platform
> Remove unnecessary init defs from sensor platform

- custom_components/solaredge_modbus_multi/hub.py
Try clearing client object on timeouts.
> Clear client object on timeout

- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/hub.py
Add RetryOnEmpty flag to const.py
> Add RetryOnEmpty flag to const.py

- custom_components/solaredge_modbus_multi/const.py
Add hostname only pattern to validator
> Add hostname only pattern to validator

- custom_components/solaredge_modbus_multi/__init__.py
- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/diagnostics.py
- custom_components/solaredge_modbus_multi/hub.py
Add advanced YAML config options. This is probably not allowed per ADR-0010, but I need a way to set advanced config that shouldn't appear in any UI dialogs.
> Add advanced YAML config options

- custom_components/solaredge_modbus_multi/hub.py
> Fix debug string format

- README.md
- custom_components/solaredge_modbus_multi/manifest.json
- hacs.json
- info.md
- requirements.txt
Might need this from 3.6.6:
https://github.com/pymodbus-dev/pymodbus/pull/2080
> Align requirements with HA 2024.3.2

- custom_components/solaredge_modbus_multi/config_flow.py
Add minor version to config flow
> Add minor version to config flow

- custom_components/solaredge_modbus_multi/hub.py
fw_version as inverter property
> Inverter fw_version as class property

- custom_components/solaredge_modbus_multi/sensor.py
Remove unit conversions in native_value for battery energy available and battery energy max.
> Remove unit conversions in native_value

- custom_components/solaredge_modbus_multi/hub.py
Handle timeouts as hub setup error during startup
> Handle timeouts as hub setup error during startup

- custom_components/solaredge_modbus_multi/hub.py
Add "looking for" debug messages before each inverter, meter, and battery class object.
> Add "looking for" debug messages

- custom_components/solaredge_modbus_multi/hub.py
- custom_components/solaredge_modbus_multi/manifest.json
MMPPT id and idstr as properties
> MMPPT id and idstr as properties

- custom_components/solaredge_modbus_multi/hub.py
ID string as serial number for MMPPT units
> ID string as serial number for MMPPT units

- README.md
- custom_components/solaredge_modbus_multi/config_flow.py
- custom_components/solaredge_modbus_multi/strings.json
- custom_components/solaredge_modbus_multi/translations/de.json
- custom_components/solaredge_modbus_multi/translations/en.json
- custom_components/solaredge_modbus_multi/translations/fr.json
- custom_components/solaredge_modbus_multi/translations/it.json
- custom_components/solaredge_modbus_multi/translations/nb.json
- custom_components/solaredge_modbus_multi/translations/nl.json
- custom_components/solaredge_modbus_multi/translations/pl.json
- hacs.json
- info.md
Reconfigure is a new feature in HA 2024.4
> Add support for config flow reconfigure

- custom_components/solaredge_modbus_multi/sensor.py
Only log battery energy warning once per occurrence
> Only log battery energy warning once per occurrence

- custom_components/solaredge_modbus_multi/binary_sensor.py
- custom_components/solaredge_modbus_multi/hub.py
- custom_components/solaredge_modbus_multi/manifest.json
Add Grid Power Available binary sensor
> Add Grid Power Available binary sensor

- custom_components/solaredge_modbus_multi/binary_sensor.py
Add POWER class to grid status binary sensor
> Add POWER class to grid status binary sensor

- custom_components/solaredge_modbus_multi/binary_sensor.py
- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/hub.py
- custom_components/solaredge_modbus_multi/manifest.json
Continue on inverter no response when reading grid on/off in case this undocumented location is not universally supported.
> Continue on inverter no response when reading grid on/off 

- custom_components/solaredge_modbus_multi/__init__.py
- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/hub.py
Remove retry_on_empty for pymodbus 3.7.0
> Remove retry_on_empty for pymodbus 3.7.0

- custom_components/solaredge_modbus_multi/hub.py
Missing keep open check after setup and add some debug logging for disconnect.
> Missing keep open check after setup

- custom_components/solaredge_modbus_multi/hub.py
Include inverter ID in meter and battery names from issue #539
> Include inverter ID in meter and battery names

- custom_components/solaredge_modbus_multi/diagnostics.py
Add serial_number key to redact list
> Add serial_number key to redact list

- custom_components/solaredge_modbus_multi/config_flow.py
- custom_components/solaredge_modbus_multi/repairs.py
Add generate_config_schema for code reuse.
> Add generate_config_schema

- custom_components/solaredge_modbus_multi/sensor.py
Add log message for battery rating setting
> Add log message for battery rating setting

- custom_components/solaredge_modbus_multi/hub.py
Remove try except wrapper from pymodbus and debug level log the pymodbus version.
> Remove try except wrapper from pymodbus

- custom_components/solaredge_modbus_multi/hub.py
Remove kwargs from modbus calls
> Remove kwargs from modbus calls

- custom_components/solaredge_modbus_multi/config_flow.py
Options handler takes no arguments
> Options handler takes no arguments

- README.md
- custom_components/solaredge_modbus_multi/button.py
- custom_components/solaredge_modbus_multi/hub.py
- custom_components/solaredge_modbus_multi/manifest.json
- custom_components/solaredge_modbus_multi/number.py
- custom_components/solaredge_modbus_multi/select.py
- custom_components/solaredge_modbus_multi/switch.py
- hacs.json
- requirements.txt
Pymodbus 3.8 write function updates.
> Pymodbus 3.8 write functions

- custom_components/solaredge_modbus_multi/diagnostics.py
- custom_components/solaredge_modbus_multi/helpers.py
* Format nested dicts in diagnostics
* Improvements in float_to_hex
> Format nested dicts in diagnostics 

- custom_components/solaredge_modbus_multi/diagnostics.py
- custom_components/solaredge_modbus_multi/hub.py
Add pymodbus version to diagnostics
> Add pymodbus version to diagnostics

- custom_components/solaredge_modbus_multi/hub.py
> Group fields and data lists

- custom_components/solaredge_modbus_multi/hub.py
Add the read response to the debug log message
> More debug for modbus reads

- custom_components/solaredge_modbus_multi/const.py
- custom_components/solaredge_modbus_multi/hub.py
Explicitly set pymodbus retries value
> Explicitly set pymodbus retries value

- custom_components/solaredge_modbus_multi/hub.py
Add retries value to connect debug
> Add retries value to connect debug

- custom_components/solaredge_modbus_multi/hub.py
- custom_components/solaredge_modbus_multi/manifest.json
Fix ModbusIOException not iterable error and handle ModbusIOException as a non-fatal exception (debug log only).
> Fix ModbusIOException not iterable error

- custom_components/solaredge_modbus_multi/config_flow.py
- custom_components/solaredge_modbus_multi/hub.py
> Format with ruff

- custom_components/solaredge_modbus_multi/hub.py
Ensure hub reconnects after optional failures.
> Ensure hub reconnects after optional failures

- .github/workflows/linter.yml
> Only validate changed files

- .github/workflows/linter.yml
Disable Pyink validation in linter workflow
> Disable Pyink validation in linter workflow
