WillCodeForCats/solaredge-modbus-multi

README.md
custom_components/solaredge_modbus_multi/__init__.py
custom_components/solaredge_modbus_multi/config_flow.py
custom_components/solaredge_modbus_multi/const.py
custom_components/solaredge_modbus_multi/hub.py
custom_components/solaredge_modbus_multi/strings.json
custom_components/solaredge_modbus_multi/translations/de.json
custom_components/solaredge_modbus_multi/translations/en.json
custom_components/solaredge_modbus_multi/translations/nb.json
custom_components/solaredge_modbus_multi/translations/nl.json
custom_components/solaredge_modbus_multi/translations/pl.json
info.md

* Adds new option "Keep Modbus Connection Open". When enabled, the integration won't close the connection after each polling cycle. Default is disabled.
* Allows poling intervals down to 1 second. For any interval under 10 seconds, it will force "Keep Modbus Connection Open" to be enabled even if disabled in options (a warning will be logged).

New config option: keep connection open

---

custom_components/solaredge_modbus_multi/helpers.py
custom_components/solaredge_modbus_multi/sensor.py

Some float values were being incorrectly validated, add helper to fix.

Battery value checks

---

custom_components/solaredge_modbus_multi/__init__.py
custom_components/solaredge_modbus_multi/hub.py

Shut down hub before unloading. Observed a problem while deleting the integration would not actually remove it from the list of configured integrations, and a second delete would cause a home assistant exception requiring a reboot.

Shut down hub before unloading

---

custom_components/solaredge_modbus_multi/hub.py
custom_components/solaredge_modbus_multi/manifest.json
custom_components/solaredge_modbus_multi/sensor.py

This attempts to resolve the issue of duplicate meters appearing after initial setup.
Some inverters do not provide stable meter model and serial number information for unknown reasons. Unfortunately choosing to base the entity Unique ID on either of these values causes new entities to be created if the inverter suddenly reports different values.
The issue has not been observed in the inverter information, so this PR changes the Unique ID for meter entities to be based on the parent inverter's model and serial number.

Duplicate meters after initial setup

---

custom_components/solaredge_modbus_multi/const.py

Add typing to unit constants not available in Home Assistant.

Add typing to constants

---

custom_components/solaredge_modbus_multi/hub.py
custom_components/solaredge_modbus_multi/manifest.json

Use DeviceInvalid exception for duplicate serial number detection instead of DeviceInitFailed

Use DeviceInvalid exception for duplicate serial

---

custom_components/solaredge_modbus_multi/__init__.py

Suppress warning in logs if option is already enabled.
Fix suggested by @spali

Check keep_modbus_open value in coordinator init

---

custom_components/solaredge_modbus_multi/hub.py

The device ID for meters and batteries should have been updated to match the unique ID change needed to address issue #61, otherwise a device with no entities after integration reload can appear.
This PR corrects an oversight that should have changed this as part of PR #83.

Use uid_base for device identifier

---

custom_components/solaredge_modbus_multi/sensor.py

This PR will make sensors that are specific to three phase devices disabled by default on single or split phase devices.

Sensor registry defaults for single vs. three phase

---

custom_components/solaredge_modbus_multi/__init__.py

Some inverters may not respond as quickly as others to all the things we ask during setup or not at all (which triggers modbus timeout), requiring a longer timeout at the coordinator level, especially with higher inverter counts.

Increase coordinator timeout to 30 seconds

---

custom_components/solaredge_modbus_multi/hub.py

This warning is redundant and superseded by the warnings added in PR #149
Known issues with battery stuff is covered in the wiki.
Replaces PR #150

Remove battery enabled warning

---

custom_components/solaredge_modbus_multi/__init__.py
custom_components/solaredge_modbus_multi/const.py
custom_components/solaredge_modbus_multi/hub.py
custom_components/solaredge_modbus_multi/number.py
custom_components/solaredge_modbus_multi/select.py

Add support for control of the "storedge control block" in SolarEdge inverters. This block is at address 0xE004-0xE011 inclusive (decimal 57348-57371). The block contains registers which allow configuration of the behaviour of any batteries connected to the inverter, such as forcing charge/discharge modes, enabling/disabling charging from AC, etc.
For any inverters that have batteries connected, create select and number entities to allow interaction with these controls.
This PR is similar to the one I did for the original version of this component https://github.com/binsentsu/home-assistant-solaredge-modbus/pull/38 - but due to the many improvements made by @WillCodeForCats this version is much better:
- Dynamic availability of controls based up selected modes
- Proper limits for number …

Add support for storedge control

---

custom_components/solaredge_modbus_multi/hub.py

Commands will request a refresh immediately but it's possible this happens too fast for real inverters and they reject the connection, whereas it works fine in my simulator.

Remove disconnect call after write

---

custom_components/solaredge_modbus_multi/__init__.py
custom_components/solaredge_modbus_multi/binary_sensor.py

Adds sensor to show status of advanced power control. Not 100% sure if this should be implemented as a binary sensor, as a switch, or both.
Right now leaning towards always show the binary sensor and then only show the switch if advanced power control is enabled in options.

Advanced Power Control binary sensor

---

custom_components/solaredge_modbus_multi/sensor.py

Multiple separate sensors with static values should be depreciated. The data they provide is available as attributes in each device's `sensor.solaredge_*_device` sensor. These sensors are no longer included in testing.
Docstring only change.

Note depreciated sensors

---

custom_components/solaredge_modbus_multi/manifest.json
requirements.txt

pymodbus 3.0.1 was flagged as a faulty release.

Bump pymodbus to 3.0.2

---

custom_components/solaredge_modbus_multi/hub.py

Logs a warning if depreciated sensors (see discussion #168) are enabled.
No change to defaults, the default behavior is to only use the single "Device" entity.

Log warning for depreciated sensors if enabled

---

custom_components/solaredge_modbus_multi/const.py
custom_components/solaredge_modbus_multi/number.py

Meter modes are selecting which meter type to use for calculating export limitation, change names to reflect that.
[Adjust limit control names closer to SetApp names](https://github.com/WillCodeForCats/solaredge-modbus-multi/pull/181/commits/6bb47a2350f275b41e00538f29b36961665bb899)

Update meter related names

---

custom_components/solaredge_modbus_multi/sensor.py

Other accumulator data for meters and inverters goes unavailable when zero (i.e. "not accumulated" state per sunspec), extend the same behavior to battery energy accumulators.

Battery energy in zero state behavior

---

custom_components/solaredge_modbus_multi/__init__.py
custom_components/solaredge_modbus_multi/config_flow.py
custom_components/solaredge_modbus_multi/const.py

List of constants to import for config was getting too long. Using enums makes the imports shorter.

Config flow cleanup

---

custom_components/solaredge_modbus_multi/__init__.py
custom_components/solaredge_modbus_multi/config_flow.py
custom_components/solaredge_modbus_multi/const.py
custom_components/solaredge_modbus_multi/hub.py
custom_components/solaredge_modbus_multi/strings.json
custom_components/solaredge_modbus_multi/translations/de.json
custom_components/solaredge_modbus_multi/translations/en.json
custom_components/solaredge_modbus_multi/translations/nb.json
custom_components/solaredge_modbus_multi/translations/nl.json
custom_components/solaredge_modbus_multi/translations/pl.json

Add inverter command delay option which delays further requests after an inverter command is sent to allow the inverter time to execute the command. Valid range is 0 to 10 seconds, where 0 disables the delay. Default is 3 seconds.

Add inverter command delay option

---

custom_components/solaredge_modbus_multi/config_flow.py

Probably harmless to allow a long command delay since it's up to the user to choose the best value for their setup.

Allow command delay up to 60 seconds

---

custom_components/solaredge_modbus_multi/manifest.json
requirements.txt

Change pymodbus version requirement to minimum instead of exact version.

Min required pymodbus 3.0.2 or greater

---

custom_components/solaredge_modbus_multi/hub.py

Clearly log an error message when pymodbus is missing or unsupported.

Error message for missing or unsupported pymodbus

---

custom_components/solaredge_modbus_multi/manifest.json

Add loggers to manifest so you can enable/disable debug logging in the UI instead of having to edit a file.

Enable debug logging through UI

---

custom_components/solaredge_modbus_multi/const.py
custom_components/solaredge_modbus_multi/sensor.py

I am not a python dev so be gentle ;) 
I'd already noticed a couple of discussions on this topic, but I have been running this tweak and it seems to fix it, from what I can gather on previous versions of the EnergyBank you end up in a situation where the available energy dips well below the rated - I opened a support ticket and they bumped firmware and config which immediately caused SoH to jump, but as a consequence a full charge now is slightly higher than the rated capacity. 
For a brand new battery this isn't entirely unexpected, but obviously causes the validation to fail - adding a 3% fudge factor seems to work for me and I would expect beyond 3% to be a problem with the BMS not a real value - but its a finger in the air figure. 
Also added is the completely undocumented status 6 …

Tweaks for Battery Validation and Status

---

custom_components/solaredge_modbus_multi/sensor.py

SensorDeviceClass.ENERGY can't be combined with SensorStateClass.MEASUREMENT as of HA 2023.2

Fix device/state class incompatibility

---

README.md
custom_components/solaredge_modbus_multi/manifest.json
hacs.json
info.md
requirements.txt

HA core is getting pymodbus 3.1.1, change our requirements to pymodbus>=3.1.1
Merge after there's an HA release with it and update our min required HA version to match.

HA core is getting pymodbus 3.1.1

---

custom_components/solaredge_modbus_multi/sensor.py

Change log level from `warning` to `debug` to avoid excess logging outside of debug mode.

Change battery energy reset logging level

---

custom_components/solaredge_modbus_multi/sensor.py

Always show meter event attributes, even if the event is not defined.

Always show meter event attributes

---

custom_components/solaredge_modbus_multi/__init__.py
custom_components/solaredge_modbus_multi/hub.py

Add logic to retry a polling cycle updates if it initially fails. The idea is to try to avoid "unavailable" states when random inverter connection problems happen by retrying a few times before giving up and going unavailable.

Retry polling cycle updates

---

custom_components/solaredge_modbus_multi/const.py
custom_components/solaredge_modbus_multi/number.py

Remove max value for storage charge/discharge setting and use a fixed value instead.
SolarEdge modbus only supports two batteries, making systems with a third battery invisible to the integration. The integration can't know a third battery exists or calculate what a third battery means to charge/discharge limits.

New const for storage charge/discharge limit

---

custom_components/solaredge_modbus_multi/diagnostics.py
custom_components/solaredge_modbus_multi/hub.py

Add inverter capability flags to diagnostics to avoid having to go into debug mode to find out if the inverter reported these functions as available or not.

Add inverter capability flags to diagnostics

---

custom_components/solaredge_modbus_multi/hub.py
custom_components/solaredge_modbus_multi/manifest.json

Consolidated inverter and meter ident and data reads into a single read. It was observed in issue #317 that larger installations can have multi-second delays between consecutive reads, which can lead to a coordinator timeout as the number of devices increases.
Originally had ident and data as separate reads to raise exception on ident check before reading data.

Modbus read consolidation

---

custom_components/solaredge_modbus_multi/select.py
custom_components/solaredge_modbus_multi/switch.py

Update availability property for limit controls since they were showing up in weird ways if limit control was enabled on inverters that don't support limit control over modbus.

Update availability property for limit controls

---

custom_components/solaredge_modbus_multi/switch.py

Can't subclass similar in select entity, remove subclass here for consistency between select and switch entities for the same dict keys.

Revert subclass in switch entity

---

custom_components/solaredge_modbus_multi/__init__.py
custom_components/solaredge_modbus_multi/config_flow.py
custom_components/solaredge_modbus_multi/const.py
custom_components/solaredge_modbus_multi/hub.py
custom_components/solaredge_modbus_multi/manifest.json
custom_components/solaredge_modbus_multi/sensor.py
custom_components/solaredge_modbus_multi/strings.json
custom_components/solaredge_modbus_multi/translations/de.json
custom_components/solaredge_modbus_multi/translations/en.json
custom_components/solaredge_modbus_multi/translations/fr.json
custom_components/solaredge_modbus_multi/translations/nb.json
custom_components/solaredge_modbus_multi/translations/nl.json
custom_components/solaredge_modbus_multi/translations/pl.json

* Remove zero condition to register value reset when allow battery energy reset option is enabled.
* Add new option to require N number of update cycles before battery energy resets (default 0)

Update battery energy reset options

---

custom_components/solaredge_modbus_multi/const.py
doc/battery_specs.txt

This PR changed the maximum display voltage for batteries up to 1000VDC, which as far as I'm aware will never actually occur with current hardware.
This change was made after it was reported that a 48VDC nominal system was reporting voltages above 800, although inaccurate (see issue #370).
Maybe it needs to be scaled by some multiplier or something, but the integration has no way to know that, and this allows for the possibility of using a template sensor to adjust it by comparing to an accurate voltage reading.

Change batt VDC upper limit to 1000

---

custom_components/solaredge_modbus_multi/__init__.py
custom_components/solaredge_modbus_multi/button.py

Add refresh button entity. Pressing it schedules an immediate polling/update cycle.
Feature requested in discussion #373.

Add refresh button entity

---

custom_components/solaredge_modbus_multi/hub.py

Change battery device check to 'and' since it was observed a battery stopped reporting one of the three device strings we were checking for to determine if a battery was attached in a slot or not.

Change battery device check

---

custom_components/solaredge_modbus_multi/__init__.py
custom_components/solaredge_modbus_multi/button.py
custom_components/solaredge_modbus_multi/const.py
custom_components/solaredge_modbus_multi/hub.py

In a multi-inverter system, if any of the followers go offline skip them and keep updating inverters that are still online instead of going offline completely.

302 skip offline inverters when updating

---

custom_components/solaredge_modbus_multi/hub.py

Use battery rating value for detection instead of make/model/firmware strings since there have been multiple reports one of the three strings returns blank. Current behavior requires all three to be >0 to detect a battery.
This PR moves away from make/model/firmware strings and uses reported capacity rating. If >0 then use battery, if <0 then mark as unusable.

Use battery rating value for detection

---

custom_components/solaredge_modbus_multi/hub.py

This may be required for solaredge dual function meters (one meter configured to perform as two i.e. production + consumption or production + E/I). Continue to log warning but allow the device with a duplicate serial number to be created. 
Devices can always be manually disabled from within Home Assistant if this created phantom meters, but I've seen enough debug and diagnostic files to where I've not seen duplicates in this manner before and it should be safe.

Allow duplicate serial number on meters

---

custom_components/solaredge_modbus_multi/__init__.py
custom_components/solaredge_modbus_multi/config_flow.py
custom_components/solaredge_modbus_multi/const.py
custom_components/solaredge_modbus_multi/hub.py
custom_components/solaredge_modbus_multi/strings.json
custom_components/solaredge_modbus_multi/translations/de.json
custom_components/solaredge_modbus_multi/translations/en.json
custom_components/solaredge_modbus_multi/translations/fr.json
custom_components/solaredge_modbus_multi/translations/nb.json
custom_components/solaredge_modbus_multi/translations/nl.json
custom_components/solaredge_modbus_multi/translations/pl.json

Solution to issue #394 is to make discovery of additional functions a config option since increasing timeout did not work (at least version 3.3.1 of pymodbus).

Revert modbus client timeout option

---

custom_components/solaredge_modbus_multi/__init__.py
custom_components/solaredge_modbus_multi/binary_sensor.py
custom_components/solaredge_modbus_multi/config_flow.py
custom_components/solaredge_modbus_multi/const.py
custom_components/solaredge_modbus_multi/hub.py
custom_components/solaredge_modbus_multi/sensor.py
custom_components/solaredge_modbus_multi/strings.json
custom_components/solaredge_modbus_multi/switch.py
custom_components/solaredge_modbus_multi/translations/de.json
custom_components/solaredge_modbus_multi/translations/en.json
custom_components/solaredge_modbus_multi/translations/fr.json
custom_components/solaredge_modbus_multi/translations/nb.json
custom_components/solaredge_modbus_multi/translations/nl.json
custom_components/solaredge_modbus_multi/translations/pl.json

Make discovery reads for advanced power control and global power control a config option. Default enabled (current behavior).
Replaces PR #413
Disable this option as a workaround for issue #394

Auto-Detect Additional Entities Option

---

custom_components/solaredge_modbus_multi/config_flow.py
custom_components/solaredge_modbus_multi/strings.json
custom_components/solaredge_modbus_multi/translations/de.json
custom_components/solaredge_modbus_multi/translations/en.json
custom_components/solaredge_modbus_multi/translations/fr.json
custom_components/solaredge_modbus_multi/translations/nb.json
custom_components/solaredge_modbus_multi/translations/nl.json
custom_components/solaredge_modbus_multi/translations/pl.json

Move inverter command delay to top level since this can now also apply to Auto-Detect Additional Entities even when Power Control Options is disabled.

Move inverter command delay option to top level

---

README.md
custom_components/solaredge_modbus_multi/__init__.py
hacs.json
info.md

New minimum requirement HA 2023.8 and Python 3.11

Move to asyncio.timeout from async_timeout

---

custom_components/solaredge_modbus_multi/number.py
custom_components/solaredge_modbus_multi/sensor.py

Add number entities to set Active Power Limit (default enabled) and CosPhi (default disabled) values.
Add docstrings and update registry defaults for matching sensor entities (enabled by default when available).

Add dynamic power control settings

---

custom_components/solaredge_modbus_multi/hub.py
custom_components/solaredge_modbus_multi/number.py
custom_components/solaredge_modbus_multi/switch.py

Static classes from pymodbus `constants` module are now inheriting from`enum.Enum` and using `UPPER_CASE` naming scheme.
Change is required for Pymodbus 3.5.1 used in Home Assistant 2023.9.1
Home Assistant 2023.9.0 uses Pymodbus 3.4.1

Pymodbus constants from enum.Enum

---

README.md
custom_components/solaredge_modbus_multi/manifest.json
requirements.txt

Bump deps Pymodbus 3.5.2 to match HA 2023.9.2
Do not see any changes that would break backwards compat with 2023.9.1 so not changing HA min version.

Pymodbus 3.5.2

---

custom_components/solaredge_modbus_multi/manifest.json
requirements.txt

Creating a new release every time pymodbus updates in HA core is a lot of extra work if it's not an update that has any breaking API changes.

Use minimum instead of pinning pymodbus version

---

README.md
custom_components/solaredge_modbus_multi/manifest.json
info.md
requirements.txt

pymodbus 3.5.3 contains a fix for an option we use in pymodbus-dev/pymodbus/pull/1795

Bump min pymodbus version to 3.5.4

---

custom_components/solaredge_modbus_multi/hub.py

Add object type to debug logging

Add object type to debug logging

---

custom_components/solaredge_modbus_multi/number.py

Handle available TypeError in number platform

Handle available TypeError in number platform

---

custom_components/solaredge_modbus_multi/number.py

In issue #461 site limit is being reported as a negative number. I'm not sure what the reason behind this is, but this PR overrides values < 0 as zero and make the entity available.

Site limit values less than 0 display as 0 instead of unavailable

---

custom_components/solaredge_modbus_multi/const.py

Follow [Home Assistant ADR-0020
](https://github.com/home-assistant/architecture/blob/master/adr/0020-minimum-supported-python-version.md)

Remove support for Python versions older than 3.11

---

custom_components/solaredge_modbus_multi/number.py

I missed updating this one before, now it causes a warning in HA 2024.1

Use UnitOfTime enum class

---

custom_components/solaredge_modbus_multi/sensor.py

Only log energy 'went backwards' once per event

Only log energy 'went backwards' once per event

---

custom_components/solaredge_modbus_multi/hub.py
custom_components/solaredge_modbus_multi/sensor.py

This PR changes the following battery device attributes into sensors:
* batt_charge_peak
* batt_discharge_peak
* batt_max_charge
* batt_max_discharge
These are listed as "nameplate" values in specs which implies static information, but it was bought to my attention that these values can actually change. Values that are dynamic in their own right should be implemented as sensors.

Battery charge/discharge power as sensors

---

custom_components/solaredge_modbus_multi/switch.py

Rename grid control switch to match binary sensor

Rename grid control switch to match binary sensor

---

custom_components/solaredge_modbus_multi/number.py

Add Power Reduce number entity. Limits the inverter’s maximum output power. The power limit can be set to any value between 0-100 [% of nominal active power].
Disabled by default since this is similar to the dynamic control Active Power Limit.
This setting is different since should be saved by the inverter.

Add Power Reduce number entity

---

custom_components/solaredge_modbus_multi/number.py

Add Current Limit number entity. Limits the inverter’s maximum output current. The current limit can be set to any value between 0 and inverter max AC current (values higher will be ignored).

Add Current Limit number entity

---

custom_components/solaredge_modbus_multi/__init__.py
custom_components/solaredge_modbus_multi/hub.py

Disconnect and retry on timeouts, with timeout limit.
Observed a case where inverter may be slow to respond causing timeouts. Forcing a disconnect within the retry cycle might help.

Disconnect and retry on timeouts

---

custom_components/solaredge_modbus_multi/__init__.py

Remove keep modbus open requirement for polling intervals less than 10 seconds.

Remove keep modbus open requirement

---

custom_components/solaredge_modbus_multi/hub.py

These were supposed to be debug level logging outside of the pre-releases.

Change log level to debug for refresh timeouts

---

custom_components/solaredge_modbus_multi/hub.py

Always read grid status. This can't be combined under "extras" because inverters that have the no response issue for power control registers can support this location.

Always read grid status

---

custom_components/solaredge_modbus_multi/config_flow.py

Calling self._abort_if_unique_id_configured() handles this condition.

Remove redundant code for unique id check

---

custom_components/solaredge_modbus_multi/const.py

Multiple reports that SolarEdge has changed something in recent firmware that causes the inverter to hang with no response when requesting registers that it doesn't support. The old behavior would return an modbus error that we could detect.
Because this is becoming a common complaint and the problem is with SolarEdge firmware that I can't fix, consider changing the integration default for Auto-Detect Additional Entities to default disabled. This will only affect new hubs. Existing setups will need a different solution to be more user friendly.

Disable option Auto-Detect Additional Entities by default

---

README.md
custom_components/solaredge_modbus_multi/sensor.py
hacs.json

`2024-08-28 12:14:46.197 WARNING (ImportExecutor_0) [homeassistant.const] POWER_VOLT_AMPERE_REACTIVE was used from solaredge_modbus_multi, this is a deprecated constant which will be removed in HA Core 2025.9. Use UnitOfReactivePower.VOLT_AMPERE_REACTIVE instead, please report it to the author of the 'solaredge_modbus_multi' custom integration`

Use UnitOfReactivePower class enum

---

custom_components/solaredge_modbus_multi/manifest.json

Pymodbus 3.8 contains API changes to the modbus exceptions enum (removes it) which is not backwards compatible.
May need to abstract or create our own class enum to be compatible with 3.6, 3.7, and 3.8.

Add requirement for pymodbus <3.8

---

custom_components/solaredge_modbus_multi/const.py
custom_components/solaredge_modbus_multi/hub.py

Add my own class for ModbusExceptions constants used in pymodbus <3.8.0 to try and deal with unknown loading of incompatible modbus reported in issue #710 .

ModbusExceptions constant class

---

README.md
custom_components/solaredge_modbus_multi/config_flow.py
hacs.json

Update options flow for HA 2024.12.0. OptionsFlow class now sets config_entry, so we don't need to do that anymore.

Update options flow for HA 2024.12.0

---

custom_components/solaredge_modbus_multi/__init__.py
custom_components/solaredge_modbus_multi/config_flow.py
custom_components/solaredge_modbus_multi/manifest.json
custom_components/solaredge_modbus_multi/repairs.py
custom_components/solaredge_modbus_multi/strings.json
custom_components/solaredge_modbus_multi/translations/de.json
custom_components/solaredge_modbus_multi/translations/en.json
custom_components/solaredge_modbus_multi/translations/fr.json
custom_components/solaredge_modbus_multi/translations/it.json
custom_components/solaredge_modbus_multi/translations/nb.json
custom_components/solaredge_modbus_multi/translations/nl.json
custom_components/solaredge_modbus_multi/translations/pl.json

Change config entry unique ID to address string. This will allow device entries to share the same IP address (i.e. modbus proxy issue #638), but port must still be unique per hub/entry.

Change config entry unique ID to address string

---

custom_components/solaredge_modbus_multi/translations/de.json
custom_components/solaredge_modbus_multi/translations/nb.json
custom_components/solaredge_modbus_multi/translations/nl.json
custom_components/solaredge_modbus_multi/translations/pl.json

Some translations for Power Control Options didn't get updated, check all translations for this key and update.

Update translations for advanced_power_control key

---

custom_components/solaredge_modbus_multi/const.py
custom_components/solaredge_modbus_multi/hub.py
custom_components/solaredge_modbus_multi/manifest.json

Add required pymodbus version startup check.

Add required pymodbus version startup check

---

custom_components/solaredge_modbus_multi/const.py
custom_components/solaredge_modbus_multi/hub.py
custom_components/solaredge_modbus_multi/manifest.json
custom_components/solaredge_modbus_multi/strings.json
custom_components/solaredge_modbus_multi/translations/de.json
custom_components/solaredge_modbus_multi/translations/en.json
custom_components/solaredge_modbus_multi/translations/fr.json
custom_components/solaredge_modbus_multi/translations/it.json
custom_components/solaredge_modbus_multi/translations/nb.json
custom_components/solaredge_modbus_multi/translations/nl.json
custom_components/solaredge_modbus_multi/translations/pl.json

Attempt to work around reported issues with detection and certain versions of SolarEdge firmware.

Add async with timeout to detect extras

---

custom_components/solaredge_modbus_multi/hub.py
custom_components/solaredge_modbus_multi/manifest.json

Update ExceptionResponse import for pymodbus 3.11 with fallback to previous import for pymodbus 3.9

Update ExceptionResponse import for pymodbus 3.11
